routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/** Application Custom Routes */
Route::resource('questions', 'QuestionsController')->except('show');
// nested route(answers nested inside questions)
Route::resource('questions.answers', 'AnswersController')->except(['index', 'create', 'show']);
Route::get('questions/{slug}', 'QuestionsController@show')->name('questions.show');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $fillable = ['user_id', 'question_id', 'votes_count', 'body'];

    /** Association with User Model */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /** Association with Question Model */
    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    /** Accessor body_html */
    public function getBodyHtmlAttribute()
    {
        return \Parsedown::instance()->text($this->body);
    }

    /** Increment answers_count when answer is created via created event */
    public static function boot()
    {
        parent::boot();

        // Increment when created
        static::created(function($answer) {
            $answer->question->increment('answers_count');
        });

        // Decrement when deleted
        static::deleted(function($answer) {
            $answer->question->decrement('answers_count');
        });

    }

    /** Accessor creation date */
    public function getCreationDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    /** Accessor answer status */
    public function getStatusAttribute()
    {
        return $this->id = $this->question->best_answer_id ? 'vote-accepted' : '';
    }
}

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Question;
use Illuminate\Http\Request;

class AnswersController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param Question $question
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Question $question,Request $request)
    {
        // Validation
        $request->validate([
            'body' => 'required'
        ]);
        // Save in DB(since Question hasMany Answers)
        $question->answers()->create([
            'body' => $request->body,
            'user_id' => auth()->id()
        ]);

        // Redirect back after submit answer
        return back()->with('success', 'Answer submitted');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Question $question
     * @param  \App\Answer $answer
     * @return void
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(Question $question, Answer $answer)
    {
        // Only authorized user
        $this->authorize('update', $answer);

        return view('answers.edit', compact('answer', 'question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Question $question
     * @param  \App\Answer $answer
     * @return void
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(Request $request, Question $question, Answer $answer)
    {
        // Only authorized user: update is the name of the policy action
        $this->authorize('update', $answer);

        // Validation and update
        $answer->update($request->validate([
            'body' => 'required|min:3'
        ]));

        // Redirection: Remember that the show route need slug
        return redirect()->route('questions.show', $question->slug)->with('success', 'Answer has been updated successfully!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question,Answer $answer)
    {
        // Only authorized user: delete is the name of policy action
        $this->authorize('delete', $answer);

        // Delete the answer
        $answer->delete();

        // Redirect back
        return back()->with('success', 'Answer deleted successfully!');
    }
}

resources/views/answers/create.blade.php
<div class="row mt-5">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h3>Your Answer</h3>
                </div>
                <hr>
                <form action="{{ route('questions.answers.store', $question->id) }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <textarea name="body" cols="30" rows="7" class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}"></textarea>
                        @if($errors->has('body'))
                            <div class="invalid-feedback">{{ $errors->first('body') }}</div>
                        @endif
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-block btn-primary">Submit your answer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="row mt-5">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-title">
                                <h2>Edit answer for Question: {{ $question->title }} </h2>
                            </div>
                            <hr>
                            <form action="{{ route('questions.answers.update', [$question->id, $answer->id]) }}"
                                  method="POST">
                                @csrf
                                @method('PATCH')
                                <div class="form-group">
                                    <textarea name="body" cols="30" rows="7"
                                              class="form-control {{ $errors->has('body', $answer->body) ? 'is-invalid' : '' }}">{{ old('body',$answer->body) }}</textarea>
                                    @if($errors->has('body'))
                                        <div class="invalid-feedback">{{ $errors->first('body') }}</div>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-block btn-primary">Submit your answer</button>
                                </div>
                            </form>
                            <a href="{{ route('questions.show', $question->slug) }}" class="btn btn-block btn-dark">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/answers/index.blade.php
<div class="row mt-5">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h2>{{ $answersCount . " " . str_plural('Answer', $answersCount)  }}</h2>
                </div>
                <hr>
                {{-- Display messages --}}
                @include('partials._messages')

                @foreach($answers as $answer)
                    <div class="media">
                        <div class="d-flex flex-column votes-control">
                            <a href="#" class="vote-up" title="This answer is useful">
                                <i class="fa fa-caret-up fa-4x" aria-hidden="true"></i>
                            </a>
                            <span class="votes-count">12</span>
                            <a href="#" class="vote-down off" title="This answer is not useful">
                                <i class="fa fa-caret-down fa-4x" aria-hidden="true"></i>
                            </a>
                            <a href="#" title="This is the best answer" class="mt-21 {{ $answer->status }}">
                                <i class="fa fa-check fa-2x" aria-hidden="true"></i>
                            </a>
                        </div>
                        <div class="media-body">
                            {!! $answer->body_html !!}
                            <div class="row">
                                <div class="col-4">
                                    <div class="ml-auto">
                                        @can('update', $answer)
                                            <a href="{{ route('questions.answers.edit', [$question->id, $answer->id]) }}" class="btn btn-outline-success btn-sm">Edit</a>
                                        @endcan
                                        {{--Using gates delete-question--}}
                                        {{--@can('delete-question', $question)--}}
                                        {{--Using policy delete--}}
                                        @can('delete', $answer)
                                            <form action="{{ route('questions.answers.destroy', [$question->id, $answer->id]) }}" class="delete-form" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                            </form>
                                        @endcan
                                        {{--@endcan--}}
                                    </div>
                                </div>
                                <div class="col-4"></div>
                                <div class="col-4">
                                    <span class="text-muted">Answered: {{ $answer->creation_date }}</span>
                                    <div class="media">
                                        <a href="{{ $answer->user->url }}" class="pr-2">{{ $answer->user->name }}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                @endforeach
            </div>
        </div>
    </div>
</div>