routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/** Application Custom Routes */
Route::resource('questions', 'QuestionsController')->except('show');
// nested route(answers nested inside questions)
Route::resource('questions.answers', 'AnswersController')->except(['index', 'create', 'show']);
Route::get('questions/{slug}', 'QuestionsController@show')->name('questions.show');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $fillable = ['user_id', 'question_id', 'votes_count', 'body'];

    /** Association with User Model */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /** Association with Question Model */
    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    /** Accessor body_html */
    public function getBodyHtmlAttribute()
    {
        return \Parsedown::instance()->text($this->body);
    }

    /** Increment answers_count when answer is created via created event */
    public static function boot()
    {
        parent::boot();

        // Increment when created
        static::created(function($answer) {
            $answer->question->increment('answers_count');
        });

        // Decrement when deleted
        static::deleted(function($answer) {
            $answer->question->decrement('answers_count');
        });

    }

    /** Accessor creation date */
    public function getCreationDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    /** Accessor answer status */
    public function getStatusAttribute()
    {
        return $this->id = $this->question->best_answer_id ? 'vote-accepted' : '';
    }
}

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    /** fillable fields(Mass Assignment)  */
    protected $fillable = ['title', 'slug', 'body', 'views', 'votes', 'answers', 'user_id', 'best_answer_id'];

    /** Association with User Model */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /** Generate slug from title via mutator
     *  So when title is created the slug will create .
     * @param $value
     */
    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = str_slug($value);
    }
    
    /** Accessor url */
    public function getUrlAttribute()
    {
        return route('questions.show', $this->slug);
    }

    /** Accessor creation_date */
    public function getCreationDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    /** Accessor status: add css classes according the question answer status */
    public function getStatusAttribute()
    {
        if($this->answers_count) {
            // if the question answer accepted
            if($this->best_answer_id){
                return "answer-accepted";
            }
            return "answered";
        }
        return "unanswered";
    }
    
    /** Accessor body_html */
    public function getBodyHtmlAttribute()
    {
        return \Parsedown::instance()->text($this->body);
    }

    /** Association with Answer Model */
    public function answers()
    {
        return $this->hasMany(Answer::class);
    }


}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\QuestionRequest;
use App\Question;
use Illuminate\Support\Facades\Gate;

class QuestionsController extends Controller
{
    /** @var int Pagination limit */
    const PAGINATION_LIMIT = 5;

    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pageTitle = "All Questions";
        $questions = Question::with('user')->latest()->paginate(self::PAGINATION_LIMIT);
        return view('questions.index', ['questions' => $questions, 'pageTitle' => $pageTitle]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $question = new Question();
        return view('questions.create', compact('question') );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param QuestionRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(QuestionRequest $request)
    {
        // Since User has many Questions
        // create question
        $request->user()->questions()->create($request->only('title', 'body'));

        // Redirect
        return redirect()->route('questions.index')->with('success', 'Question created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        // Increment thr question views
        $question->increment('views');

        return view('questions.show', compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        // Authorization using Gates
        if(Gate::denies('update-question', $question)){
            abort(403,'Access denied');
        }
        return view('questions.edit', compact('question'));
    }

    /**
     * Update the specified resource in storage.
     * @param QuestionRequest $request
     * @param Question $question
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(QuestionRequest $request, Question $question)
    {

        /** Authorization via Gates */
        if(Gate::denies('update-question', $question)){
            abort(403,'Access denied');
        }
        $question->update($request->only('title', 'body'));

        // Redirection after update
        return redirect()->route('questions.index')->with('success', 'Question updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question $question
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Question $question)
    {
        /*
        if(Gate::denies('delete-question', $question)){
            abort(403,'Access denied');
        }
        */
        /** Authorization via Policy */
        $this->authorize('delete', $question);

        if($question->delete()){
            return redirect()->route('questions.index')->with('success', 'Question deleted');
        }
    }
}

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h3 style="margin-bottom: 0">New Question</h3>
                            <div class="ml-auto">
                                <a href="{{ route('questions.index') }}" class="btn btn-secondary">All Questions</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('questions.store') }}" method="POST">
                            @include('questions.partials._form', ['button_text' => 'Ask Question'])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h3 style="margin-bottom: 0">Edit Question</h3>
                            <div class="ml-auto">
                                <a href="{{ route('questions.index') }}" class="btn btn-secondary">All Questions</a>
                                <a href="{{ route('questions.create') }}" class="btn btn-primary">Ask Questions</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('questions.update', $question->id) }}" method="POST">
                            @method('PUT')
                            @include('questions.partials._form', ['button_text' => 'Update Question'])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h3 style="margin-bottom: 0">All Questions</h3>
                            <div class="ml-auto">
                                <a href="{{ route('questions.create') }}" class="btn btn-primary">Ask Question</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        {{-- Display messages --}}
                        @include('partials._messages')
                        @foreach($questions as $question)
                            <div class="media mb-4">
                                <div class="d-flex flex-column counters mr-5">
                                    <div class="vote">
                                        <strong>{{ $question->votes }}</strong> {{ str_plural('vote', $question->votes) }}
                                    </div>
                                    <div class="status mb-3 {{ $question->status }}">
                                        <strong>{{ $question->answers_count }}</strong> {{ str_plural('answer', $question->answers_count) }}
                                    </div>
                                    <div class="view">
                                        {{ $question->views . " " . str_plural('view', $question->views) }}
                                    </div>
                                </div>
                                <div class="media-body">
                                    <div class="d-flex align-items-center">
                                        <h3 style="margin-bottom: 0"><a href="{{ $question->url }}">{{ $question->title }}</a></h3>
                                        <div class="ml-auto">
                                            @can('update-question', $question)
                                                <a href="{{ route('questions.edit', $question->id) }}" class="btn btn-outline-success btn-sm">Edit</a>
                                            @endcan
                                                {{--Using gates delete-question--}}
                                            {{--@can('delete-question', $question)--}}
                                                {{--Using policy delete--}}
                                            @can('delete', $question)
                                                <form action="{{ route('questions.destroy', $question->id) }}" class="delete-form" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                                </form>
                                            @endcan
                                            {{--@endcan--}}
                                        </div>
                                    </div>
                                    <p class="lead">
                                        Asked by: <a href="{{ $question->user->url }}">{{ $question->user->name }}</a>
                                        <small class="text-muted">{{ $question->creation_date }}</small>
                                    </p>

                                    {{ str_limit($question->body, 250) }}
                                </div>
                            </div>
                            <hr>
                        @endforeach
                        {{--  Pagination links --}}
                        {{ $questions->links('vendor.pagination.bootstrap-4') }}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <div class="d-flex align-items-center">
                                <h2 style="margin-bottom: 0">{{ $question->title }}</h2>
                                <div class="ml-auto">
                                    <a href="{{ route('questions.index') }}" class="btn btn-secondary">All Questions</a>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="media">
                            <div class="d-flex flex-column votes-control">
                                <a href="#" class="vote-up" title="This question is useful">
                                    <i class="fa fa-caret-up fa-4x" aria-hidden="true"></i>
                                </a>
                                <span class="votes-count">12</span>
                                <a href="#" class="vote-down off" title="This question is not useful">
                                    <i class="fa fa-caret-down fa-4x" aria-hidden="true"></i>
                                </a>
                                <a href="#" title="Favorite question" class="favorite mt-21 favorited">
                                    <i class="fa fa-star fa-2x" aria-hidden="true"></i>
                                    <span class="favorites-count">234</span>
                                </a>
                            </div>
                            <div class="media-body">
                                {!! $question->body_html !!}
                                <div class="float-right">
                                    <span class="text-muted">Asked: {{ $question->creation_date }}</span>
                                    <div class="media">
                                        <a href="{{ $question->user->url }}" class="pr-2">{{ $question->user->name }}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {{-- The answers part(All answers from index) --}}
        @include('answers.index', [
            'answers' => $question->answers,
            'answersCount' => $question->answers_count
        ])

        {{-- Create the answer part(from create) --}}
        @include('answers.create')
    </div>
@endsection